-- V1: initial schema for NousBooks.
-- Portable SQL that works on both H2 (MODE=PostgreSQL, dev) and real Postgres (prod).
-- Column names follow Hibernate's default physical naming strategy (snake_case).

CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email       VARCHAR(255) NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP    NOT NULL
);

CREATE TABLE books (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_books_id VARCHAR(255) UNIQUE,
    title           VARCHAR(255),
    description     VARCHAR(2000),
    thumbnail       VARCHAR(255),
    published_date  TIMESTAMP
);

CREATE TABLE user_books (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT        NOT NULL,
    book_id      BIGINT        NOT NULL,
    status       VARCHAR(255),
    rating       INTEGER,
    review       VARCHAR(2000),
    started_at   TIMESTAMP,
    finished_at  TIMESTAMP,
    CONSTRAINT fk_user_books_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_books_book FOREIGN KEY (book_id) REFERENCES books (id),
    CONSTRAINT uq_user_books_user_book UNIQUE (user_id, book_id)
);

CREATE TABLE notes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT       NOT NULL,
    book_id     BIGINT       NOT NULL,
    title       VARCHAR(255),
    content     VARCHAR(2000),
    created_at  TIMESTAMP    NOT NULL,
    CONSTRAINT fk_notes_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_notes_book FOREIGN KEY (book_id) REFERENCES books (id)
);
